name: Cypress Tests with Install Job and UI Chrome Job x 5

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: [self-hosted,macOS,X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Cypress install
      #   uses: cypress-io/github-action@v4
      #   with:
      #     runTests: false
      #     build: npm run build

      # - name: Save build folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     if-no-files-found: error
      #     path: dist

 